### PR TITLE
Use the new PoPS kernel API

### PR DESCRIPTION
**Pull request by wenzeslaus**
CLI still the same, so translating old options to new API.

This does not contain changes to pops dir and it needs ncsu-landscape-dynamics/PoPS#27.

### CODE REVIEW

**Comment by wenzeslaus** [comment]
Current command line parameters:

```
      dispersal_kernel   Type of dispersal kernel
                         options: cauchy,cauchy_mix
                         default: cauchy
  short_distance_scale   Distance scale parameter for short range dispersal kernel
                         default: 20.57
   long_distance_scale   Distance scale parameter for long range dispersal kernel
                 kappa   Strength of the wind direction in the von-mises distribution
                         default: 2
                  wind   Prevailing wind direction
                         options: N,NE,E,SE,S,SW,W,NW,NONE
                         default: NONE
```

Options for command line parameters as discussed with by @ChrisJones687. Here version with limited directional for long distance dispersal (alternative, longer spellings and extended options in `[]`):

```
short_[distance_]dispersal_kernel   Type of dispersal kernel
                                    options: cauchy,exponential[,uniform]
                                    default: cauchy
           short_[distance_]scale   Distance scale parameter for short range dispersal kernel
                             wind   Prevailing wind direction
                                    options: N,NE,E,SE,S,SW,W,NW,NONE
                                    default: NONE
                            kappa   Strength of the wind direction in the von-mises distribution
 long_[distance_]dispersal_kernel   Type of dispersal kernel
                                    options: cauchy,exponential[,uniform]
                                    default: cauchy
            long_[distance_]scale   Distance scale parameter for long range dispersal kernel
 long_[distance_]direction[ality]   Direction[ality] of long distance dispersal
                                    options: same_as_short,none
```

Another alternative with shorter names and full options for the second dispersal kernel:

```
short_dispersal_kernel   Type of dispersal kernel
                         options: cauchy,exponential,uniform
                         default: cauchy
           short_scale   Distance scale parameter for short range dispersal kernel
       short_direction   Prevailing wind direction
                         options: N,NE,E,SE,S,SW,W,NW,NONE
                         default: NONE
           short_kappa   Strength of the wind direction in the von-mises distribution
 long_dispersal_kernel   Type of dispersal kernel
                         options: cauchy,exponential,uniform
                         default: cauchy
            long_scale   Distance scale parameter for long range dispersal kernel
        long_direction   Prevailing wind direction
                         options: N,NE,E,SE,S,SW,W,NW,NONE
                         default: NONE
            long_kappa   Strength of the wind direction in the von-mises distribution
```

Final option distinguishing the kernels by their most common use:

```
       natural_dispersal_kernel   Type of dispersal kernel
                                  options: cauchy,exponential,uniform
                                  default: cauchy
                  natural_scale   Distance scale parameter for short range dispersal kernel
              natural_direction   Prevailing wind direction
                                  options: N,NE,E,SE,S,SW,W,NW,NONE
                                  default: NONE
                  natural_kappa   Strength of the wind direction in the von-mises distribution
 anthropogenic_dispersal_kernel   Type of dispersal kernel
                                  options: cauchy,exponential,uniform
                                  default: cauchy
            anthropogenic_scale   Distance scale parameter for long range dispersal kernel
        anthropogenic_direction   Prevailing wind direction
                                  options: N,NE,E,SE,S,SW,W,NW,NONE
                                  default: NONE
            anthropogenic_kappa   Strength of the wind direction in the von-mises distribution
```

**Comment by wenzeslaus** [comment]
It gives the same results as previous version except for the change of abs to std::abs (double to int conversion) and potentially in cases when resolution was not exactly integer (again double to int problem), i.e. the results are different, but would be the same if same double to int conversions would be done.

Code used to test it (using SLF data):

```
ls -la `which r.pops.spread` && time r.pops.spread host=tree_of_heaven total_plants=total_hosts infected=initial_infections_2017_single_count output=infection_kernels output_series=infection_kernels probability=probability_kernels natural_dir=NONE temperature_coefficient_file=$LOCATION/../low_spread_temp_coefficient_slf_2018_2022.txt moisture_coeff_file=$LOCATION/../const_1_moist_coefficient_slf_2018_2022.txt lethal_temperature=-12.87 lethal_month=1 temperature_file=$LOCATION/../high_spread_crit_temp_slf_2018_2022.txt start_time=2018 end_time=2022 seasonality=6,11 step=month repro_rate=2 natural_scale=59 natural_kappa=2 random_seed=42 runs=4 nprocs=4 -l --o && r.mapcalc "diff = float(probability_kernels_stdabs - probability_kernels)" -s --o --v && r.colors map=diff color=diff && r.univar diff
```

**Comment by wenzeslaus** [comment]
@ChrisJones687, the parameters are now:

```
          natural_dispersal_kernel   Natural dispersal kernel type
                                     options: cauchy,exponential
                                     default: cauchy
                  natural_distance   Distance parameter for natural dispersal kernel
                 natural_direction   Direction of natural dispersal kernel
                                     options: N,NE,E,SE,S,SW,W,NW,NONE,none
                                     default: none
        natural_direction_strength   Strength of direction of natural dispersal kernel
    anthropogenic_dispersal_kernel   Anthropogenic dispersal kernel type
                                     options: cauchy,exponential
            anthropogenic_distance   Distance parameter for anthropogenic dispersal kernel
           anthropogenic_direction   Direction of anthropogenic dispersal kernel
                                     options: N,NE,E,SE,S,SW,W,NW,NONE,none
                                     default: none
  anthropogenic_direction_strength   Strength of direction of anthropogenic dispersal kernel
         percent_natural_dispersal   Percentage of natural dispersal
                                     options: 0-1
```

@petrasovaa, the PR is ready for a new review.

**Review by petrasovaa — APPROVED** [review]

**Comment by wenzeslaus** [comment]
The final options (with full descriptions) are:

```
#%option
#% key: natural_dispersal_kernel
#% type: string
#% required: no
#% multiple: no
#% options: cauchy,exponential
#% label: Natural dispersal kernel type
#% answer: cauchy
#% guisection: Dispersal
#%end
#%option
#% key: natural_distance
#% type: double
#% required: no
#% multiple: no
#% label: Distance parameter for natural dispersal kernel
#% guisection: Dispersal
#%end
#%option
#% key: natural_direction
#% type: string
#% required: yes
#% multiple: no
#% options: N,NE,E,SE,S,SW,W,NW,NONE,none
#% label: Direction of natural dispersal kernel
#% description: Typically prevailing wind direction; none means that there is no directionality or no wind
#% answer: none
#% guisection: Dispersal
#%end
#%option
#% key: natural_direction_strength
#% type: double
#% required: yes
#% multiple: no
#% label: Strength of direction of natural dispersal kernel
#% description: The kappa parameter of von Mises distribution (concentration); typically the strength of the wind direction
#% guisection: Dispersal
#%end
#%option
#% key: anthropogenic_dispersal_kernel
#% type: string
#% required: no
#% multiple: no
#% options: cauchy,exponential
#% label: Anthropogenic dispersal kernel type
#% guisection: Dispersal
#%end
#%option
#% key: anthropogenic_distance
#% type: double
#% required: no
#% multiple: no
#% label: Distance parameter for anthropogenic dispersal kernel
#% guisection: Dispersal
#%end
#%option
#% key: anthropogenic_direction
#% type: string
#% required: yes
#% multiple: no
#% options: N,NE,E,SE,S,SW,W,NW,NONE,none
#% label: Direction of anthropogenic dispersal kernel
#% description: Value none means that there is no directionality
#% answer: none
#% guisection: Dispersal
#%end
#%option
#% key: anthropogenic_direction_strength
#% type: double
#% required: no
#% multiple: no
#% label: Strength of direction of anthropogenic dispersal kernel
#% description: The kappa parameter of von Mises distribution (concentration); typically the strength of the wind direction
#% guisection: Dispersal
#%end
```

**Pull request merged**
